"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import dj_database_url

# .env 파일에서 환경 변수 로드
load_dotenv()

# 프로젝트 기본 경로 설정 (모든 파일 경로의 기준점)
BASE_DIR = Path(__file__).resolve().parent.parent

# 토큰 만료 시간 설정 (2시간)
TOKEN_EXPIRED_AFTER_SECONDS = 7200  # 2시간

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# 보안 키 설정 (.env 파일에서 로드하거나 기본값 사용)
SECRET_KEY = os.environ.get("SECRET_KEY")
if not SECRET_KEY:
    if DEBUG:
        # 개발 환경에서만 기본 키 사용
        SECRET_KEY = "django-insecure-dev-only-key"
    else:
        # 프로덕션 환경에서는 반드시 환경변수 설정 필요
        raise ValueError(
            "SECRET_KEY 환경변수가 설정되지 않았습니다. 프로덕션 환경에서는 필수입니다."
        )

# 디버그 모드 설정 (.env 파일에서 로드하거나 기본값으로 True 사용)
DEBUG = os.environ.get("DEBUG", "True") == "True"

# 접근 허용 호스트 설정
ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")


# Application definition

# 설치된 앱 목록 (Django 기본 앱, 서드파티 앱, 로컬 앱 포함)
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party apps
    "rest_framework",  # Django REST Framework
    "corsheaders",  # CORS 지원
    "rest_framework.authtoken",  # 토큰 기반 인증
    # Local apps
    "core",  # 핵심 모델
    "api",  # API 앱
]

# 미들웨어 설정 (요청 처리 파이프라인)
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",  # CORS 미들웨어 (API 요청 허용)
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "api.middleware.UserAccessMiddleware",  # 사용자 접근 제어 미들웨어
]

# CORS 설정 (프론트엔드에서 API 접근 허용)
CORS_ALLOWED_ORIGINS = os.environ.get(
    "CORS_ALLOWED_ORIGINS", "http://localhost:3000,http://127.0.0.1:3000"
).split(",")

# 메인 URL 설정
ROOT_URLCONF = "config.urls"

# 템플릿 설정
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# WSGI 설정 (웹 서버와 연결)
WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# 데이터베이스 설정 (PostgreSQL 사용)
DATABASES = {
    "default": dj_database_url.config(
        default=os.environ.get(
            "DATABASE_URL", "postgres://postgres:postgres@localhost:5432/pms"
        ),
        conn_max_age=600,
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

# 비밀번호 검증 설정
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

# 국제화 설정 (한국어, 서울 시간대)
LANGUAGE_CODE = "ko-kr"
TIME_ZONE = "Asia/Seoul"
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

# 정적 파일 설정
STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# 미디어 파일 설정
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# 기본 키 필드 타입
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# 사용자 정의 모델 설정
AUTH_USER_MODEL = "core.User"

# Django REST Framework 설정
REST_FRAMEWORK = {
    # 인증 클래스 설정 (토큰 인증, 세션 인증 지원)
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    # 기본 권한 설정 (인증된 사용자만 접근 가능)
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    # 페이지네이션 설정
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 100,  # 기본 페이지 크기를 100으로 증가
    "PAGE_SIZE_QUERY_PARAM": "page_size",  # 페이지 크기를 동적으로 조정할 수 있는 파라미터
    "MAX_PAGE_SIZE": 1000,  # 최대 페이지 크기 설정
}

# 세션 설정
SESSION_COOKIE_AGE = 7200  # 2시간 (초 단위)
SESSION_SAVE_EVERY_REQUEST = True  # 매 요청마다 세션 갱신

# 프로덕션 보안 설정
if not DEBUG:
    # HTTPS 설정 (프로덕션 환경)
    SECURE_SSL_REDIRECT = True  # HTTP를 HTTPS로 리다이렉트
    SECURE_HSTS_SECONDS = 31536000  # HSTS 헤더 설정 (1년)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True  # 서브도메인에도 HSTS 적용
    SECURE_HSTS_PRELOAD = True  # HSTS 프리로드 목록에 추가 가능

    # 쿠키 보안 설정
    SESSION_COOKIE_SECURE = True  # HTTPS에서만 세션 쿠키 전송
    CSRF_COOKIE_SECURE = True  # HTTPS에서만 CSRF 쿠키 전송
    SESSION_COOKIE_HTTPONLY = True  # JavaScript에서 세션 쿠키 접근 불가
    CSRF_COOKIE_HTTPONLY = True  # JavaScript에서 CSRF 쿠키 접근 불가

    # 기타 보안 헤더
    SECURE_CONTENT_TYPE_NOSNIFF = True  # MIME 타입 스니핑 방지
    SECURE_BROWSER_XSS_FILTER = True  # XSS 필터 활성화
    X_FRAME_OPTIONS = "DENY"  # 클릭재킹 방지

    # 관리자 URL 보안 강화
    ADMIN_URL = os.environ.get("ADMIN_URL", "admin/")  # 관리자 URL 커스터마이징

    # 에러 로그 보안 설정
    ADMINS = [
        # 실제 적용 - 관리자 이메일 설정 (에러 발생 시 알림)
        # ("Admin Name", "admin@yourdomain.com"),
    ]

    # 디버그 정보 완전 비활성화
    DEBUG_PROPAGATE_EXCEPTIONS = False

    # 보안 미들웨어 추가
    MIDDLEWARE.insert(0, "django.middleware.security.SecurityMiddleware")

    # 정적 파일 보안 설정
    STATICFILES_STORAGE = "django.contrib.staticfiles.storage.StaticFilesStorage"

    # 로그 레벨 강화
    for logger_name in ["django", "django.request", "api", "api.auth", "auth"]:
        if logger_name in LOGGING["loggers"]:
            LOGGING["loggers"][logger_name][
                "level"
            ] = "WARNING"  # 프로덕션에서는 WARNING 레벨 이상만 로그

# 로그 디렉토리 생성 (프로덕션 환경에서 필요)
LOG_DIR = os.path.join(BASE_DIR, "logs")
if not os.path.exists(LOG_DIR):
    os.makedirs(LOG_DIR)

# 로깅 설정
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    # 로그 포맷 설정
    "formatters": {
        "verbose": {
            "format": "[{levelname}] {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "[{levelname}] {asctime} {message}",
            "style": "{",
        },
    },
    # 로그 핸들러 설정
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
    },
    # 로거 설정 (프로덕션에서는 콘솔 로깅만 사용)
    "loggers": {
        # Django 기본 로거
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": True,
        },
        "django.request": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        # 각 앱별 로거
        "api": {
            "handlers": ["console"],
            "level": "DEBUG" if DEBUG else "INFO",
            "propagate": False,
        },
        "api.auth": {
            "handlers": ["console"],
            "level": "DEBUG" if DEBUG else "INFO",
            "propagate": False,
        },
        "auth": {
            "handlers": ["console"],
            "level": "DEBUG" if DEBUG else "INFO",
            "propagate": False,
        },
    },
}

# 개발 환경에서만 파일 로깅 사용
if DEBUG:
    LOGGING["handlers"].update(
        {
            "file": {
                "class": "logging.handlers.RotatingFileHandler",
                "filename": os.path.join(LOG_DIR, "django.log"),
                "formatter": "verbose",
                "maxBytes": 10485760,  # 10MB
                "backupCount": 5,
            },
            "auth_file": {
                "class": "logging.handlers.RotatingFileHandler",
                "filename": os.path.join(LOG_DIR, "auth.log"),
                "formatter": "verbose",
                "maxBytes": 10485760,  # 10MB
                "backupCount": 5,
            },
            "api_file": {
                "class": "logging.handlers.RotatingFileHandler",
                "filename": os.path.join(LOG_DIR, "api.log"),
                "formatter": "verbose",
                "maxBytes": 10485760,  # 10MB
                "backupCount": 5,
            },
        }
    )
    # 개발 환경에서는 파일 핸들러도 추가
    LOGGING["loggers"]["django"]["handlers"].append("file")
    LOGGING["loggers"]["django.request"]["handlers"].append("file")
    LOGGING["loggers"]["api"]["handlers"].append("api_file")
    LOGGING["loggers"]["api.auth"]["handlers"].append("auth_file")
    LOGGING["loggers"]["auth"]["handlers"].append("auth_file")
