# Generated by Django 5.0.3 on 2025-05-27 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='clinic_attended_dates',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
