# Generated by Django 5.0.3 on 2025-05-29 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_student_clinic_attended_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_subject',
            field=models.ForeignKey(default='physics1', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.subject'),
        ),
    ]
