# Generated by Django 5.0.3 on 2025-05-29 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_student_student_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_available_time',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_available_time',
        ),
    ]
