# Generated by Django 5.0.3 on 2025-06-10 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_available_time_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='expected_teacher',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='max_student_num',
            field=models.IntegerField(default=100),
        ),
    ]
