# Generated by Django 5.0.3 on 2025-06-10 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_student_expected_teacher_user_max_student_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='available_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_available_time', to='core.time'),
        ),
        migrations.AddField(
            model_name='user',
            name='available_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers_available_time', to='core.time'),
        ),
    ]
