# Generated by Django 5.0.3 on 2025-07-10 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_student_available_time_alter_student_grade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='available_time',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='clinic_time',
        ),
        migrations.RemoveField(
            model_name='student',
            name='available_time',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='clinic_students',
        ),
        migrations.RemoveField(
            model_name='student',
            name='assigned_teacher',
        ),
        migrations.RemoveField(
            model_name='student',
            name='clinic_attended_dates',
        ),
        migrations.RemoveField(
            model_name='student',
            name='expected_teacher',
        ),
        migrations.AddField(
            model_name='clinic',
            name='clinic_day',
            field=models.CharField(choices=[('mon', '월요일'), ('tue', '화요일'), ('wed', '수요일'), ('thu', '목요일'), ('fri', '금요일')], default='mon', max_length=3),
        ),
        migrations.AddField(
            model_name='clinic',
            name='clinic_prime_students',
            field=models.ManyToManyField(blank=True, related_name='enrolled_prime_clinics', to='core.student'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='clinic_sub_students',
            field=models.ManyToManyField(blank=True, related_name='enrolled_sub_clinics', to='core.student'),
        ),
        migrations.AddField(
            model_name='student',
            name='reserved_clinic',
            field=models.ManyToManyField(blank=True, related_name='reserved_students', to='core.clinic'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Time',
        ),
    ]
