# Generated by Django 5.0.3 on 2025-07-10 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_user_available_time_remove_clinic_clinic_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='clinic_unassigned_students',
            field=models.ManyToManyField(blank=True, related_name='unassigned_clinics', to='core.student'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='clinic_subject',
            field=models.ForeignKey(default='physics1', on_delete=django.db.models.deletion.CASCADE, related_name='related_clinics', to='core.subject'),
        ),
    ]
