# Generated by Django 5.0.3 on 2025-07-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_clinic_clinic_unassigned_students_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='clinic_day',
            field=models.CharField(choices=[('mon', '월요일'), ('tue', '화요일'), ('wed', '수요일'), ('thu', '목요일'), ('fri', '금요일'), ('sat', '토요일'), ('sun', '일요일')], default='mon', max_length=3),
        ),
    ]
