# Generated by Django 5.0.3 on 2025-07-23 03:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_clinic_clinic_day"),
    ]

    operations = [
        # 먼저 새로운 필드들을 추가
        migrations.AddField(
            model_name="clinic",
            name="clinic_capacity",
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name="clinic",
            name="clinic_room",
            field=models.CharField(
                choices=[
                    ("1강의실", "1강의실"),
                    ("2강의실", "2강의실"),
                    ("3강의실", "3강의실"),
                    ("4강의실", "4강의실"),
                    ("5강의실", "5강의실"),
                    ("6강의실", "6강의실"),
                    ("7강의실", "7강의실"),
                    ("8강의실", "8강의실"),
                ],
                default="1강의실",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="clinic",
            name="clinic_time",
            field=models.CharField(
                choices=[
                    ("18:00", "18:00-19:00"),
                    ("19:00", "19:00-20:00"),
                    ("20:00", "20:00-21:00"),
                    ("21:00", "21:00-22:00"),
                ],
                default="18:00",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="clinic",
            name="clinic_students",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"is_student": True},
                related_name="enrolled_clinics",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_student",
            field=models.BooleanField(default=False),
        ),
        # 기존 필드들 제거
        migrations.RemoveField(
            model_name="clinic",
            name="clinic_prime_students",
        ),
        migrations.RemoveField(
            model_name="clinic",
            name="clinic_sub_students",
        ),
        migrations.RemoveField(
            model_name="clinic",
            name="clinic_unassigned_students",
        ),
        # 마지막에 unique_together 설정 (모든 필드가 추가된 후)
        migrations.AlterUniqueTogether(
            name="clinic",
            unique_together={("clinic_day", "clinic_time", "clinic_room")},
        ),
    ]
