# Generated by Django 5.0.3 on 2025-07-23 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_clinic_unique_together_clinic_clinic_capacity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyReservationPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField()),
                ('week_end_date', models.DateField()),
                ('reservation_start', models.DateTimeField()),
                ('reservation_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', '대기중'), ('open', '예약 가능'), ('closed', '예약 마감'), ('completed', '완료')], default='pending', max_length=10)),
                ('total_clinics', models.IntegerField(default=0)),
                ('total_reservations', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-week_start_date'],
                'unique_together': {('week_start_date', 'week_end_date')},
            },
        ),
        migrations.AddField(
            model_name='clinic',
            name='weekly_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinics', to='core.weeklyreservationperiod'),
        ),
    ]
