# Generated by Django 5.0.3 on 2025-07-24 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_student_id_generated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='max_student_num',
        ),
        migrations.AddField(
            model_name='student',
            name='student_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_user_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='student_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_subject',
            field=models.ForeignKey(blank=True, default='physics1', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='core.subject'),
        ),
    ]
