# Generated by Django 5.0.3 on 2025-07-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_user_max_student_num_student_student_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='student_phone_num',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
