# Generated by Django 5.0.3 on 2025-07-24 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_studentplacement_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='clinic_capacity',
            field=models.IntegerField(default=20, verbose_name='정원'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='clinic_day',
            field=models.CharField(choices=[('mon', '월요일'), ('tue', '화요일'), ('wed', '수요일'), ('thu', '목요일'), ('fri', '금요일'), ('sat', '토요일'), ('sun', '일요일')], default='mon', max_length=3, verbose_name='클리닉 요일'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='clinic_room',
            field=models.CharField(choices=[('1강의실', '1강의실'), ('2강의실', '2강의실'), ('3강의실', '3강의실'), ('4강의실', '4강의실'), ('5강의실', '5강의실'), ('6강의실', '6강의실'), ('7강의실', '7강의실'), ('8강의실', '8강의실')], default='1강의실', max_length=10, verbose_name='강의실'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='clinic_students',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_student': True}, related_name='enrolled_clinics', to=settings.AUTH_USER_MODEL, verbose_name='예약한 학생들'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='clinic_subject',
            field=models.ForeignKey(default='physics1', on_delete=django.db.models.deletion.CASCADE, related_name='related_clinics', to='core.subject', verbose_name='과목'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='clinic_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_clinics', to=settings.AUTH_USER_MODEL, verbose_name='담당 강사'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='clinic_time',
            field=models.CharField(choices=[('18:00', '18:00-19:00'), ('19:00', '19:00-20:00'), ('20:00', '20:00-21:00'), ('21:00', '21:00-22:00')], default='18:00', max_length=5, verbose_name='클리닉 시간'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='weekly_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinics', to='core.weeklyreservationperiod', verbose_name='주간 예약 기간'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject',
            field=models.CharField(max_length=50, verbose_name='과목명'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_kr',
            field=models.CharField(default='한글과목명', max_length=50, verbose_name='한글과목명'),
        ),
        migrations.AlterField(
            model_name='user',
            name='grade',
            field=models.CharField(blank=True, choices=[('예비고1', '예비고1'), ('1학년', '1학년'), ('2학년', '2학년'), ('3학년', '3학년')], default='', max_length=10, verbose_name='학년'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(default=False, verbose_name='학생'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_teacher',
            field=models.BooleanField(default=True, verbose_name='강사'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_num',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='전화번호'),
        ),
        migrations.AlterField(
            model_name='user',
            name='school',
            field=models.CharField(blank=True, choices=[('세화고', '세화고'), ('세화여고', '세화여고'), ('연합반', '연합반')], default='', max_length=100, verbose_name='학교'),
        ),
        migrations.AlterField(
            model_name='user',
            name='student_parent_phone_num',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='학부모 전화번호'),
        ),
        migrations.AlterField(
            model_name='user',
            name='student_phone_num',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='학생 전화번호'),
        ),
        migrations.AlterField(
            model_name='user',
            name='subject',
            field=models.ForeignKey(blank=True, default='physics1', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='core.subject', verbose_name='과목'),
        ),
        migrations.AlterField(
            model_name='weeklyreservationperiod',
            name='reservation_end',
            field=models.DateTimeField(verbose_name='예약 마감 시간'),
        ),
        migrations.AlterField(
            model_name='weeklyreservationperiod',
            name='reservation_start',
            field=models.DateTimeField(verbose_name='예약 시작 시간'),
        ),
        migrations.AlterField(
            model_name='weeklyreservationperiod',
            name='status',
            field=models.CharField(choices=[('pending', '대기중'), ('open', '예약 가능'), ('closed', '예약 마감'), ('completed', '완료')], default='pending', max_length=10, verbose_name='상태'),
        ),
        migrations.AlterField(
            model_name='weeklyreservationperiod',
            name='week_end_date',
            field=models.DateField(verbose_name='주 종료 날짜'),
        ),
        migrations.AlterField(
            model_name='weeklyreservationperiod',
            name='week_start_date',
            field=models.DateField(verbose_name='주 시작 날짜'),
        ),
    ]
