# Generated by Django 5.0.3 on 2025-07-24 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_clinic_clinic_capacity_alter_clinic_clinic_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='is_active',
            field=models.BooleanField(default=False, help_text='활성화된 클리닉만 예약 가능합니다.', verbose_name='활성화 상태'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='clinic_capacity',
            field=models.IntegerField(default=6, verbose_name='정원'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='clinic_students',
            field=models.ManyToManyField(blank=True, default=None, limit_choices_to={'is_student': True}, related_name='enrolled_clinics', to=settings.AUTH_USER_MODEL, verbose_name='예약한 학생들'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='clinic_teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_teacher': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_clinics', to=settings.AUTH_USER_MODEL, verbose_name='담당 강사'),
        ),
    ]
