# Generated by Django 5.0.3 on 2025-07-24 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_clinic_clinic_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='clinic_students',
            field=models.ManyToManyField(blank=True, default=None, limit_choices_to={'is_student': True}, related_name='enrolled_clinics', to=settings.AUTH_USER_MODEL, verbose_name='예약한 학생들'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='clinic_teacher',
            field=models.ForeignKey(blank=True, default=1, limit_choices_to={'is_teacher': True}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_clinics', to=settings.AUTH_USER_MODEL, verbose_name='담당 강사'),
            preserve_default=False,
        ),
    ]
