# Generated by Django 5.0.3 on 2025-07-25 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_clinic_teacher_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP 주소')),
                ('forwarded_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='프록시 IP')),
                ('user_agent', models.TextField(verbose_name='User Agent')),
                ('device_type', models.CharField(default='unknown', max_length=20, verbose_name='기기 유형')),
                ('os_name', models.CharField(default='unknown', max_length=50, verbose_name='운영체제')),
                ('browser_name', models.CharField(default='unknown', max_length=50, verbose_name='브라우저')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='국가')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='도시')),
                ('isp', models.CharField(blank=True, max_length=100, null=True, verbose_name='ISP')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True, verbose_name='세션 키')),
                ('token_key', models.CharField(blank=True, max_length=40, null=True, verbose_name='토큰 키')),
                ('login_success', models.BooleanField(default=True, verbose_name='로그인 성공 여부')),
                ('failure_reason', models.CharField(blank=True, max_length=100, null=True, verbose_name='실패 사유')),
                ('logout_reason', models.CharField(blank=True, max_length=50, null=True, verbose_name='로그아웃 사유')),
                ('login_at', models.DateTimeField(auto_now_add=True, verbose_name='로그인 시간')),
                ('logout_at', models.DateTimeField(blank=True, null=True, verbose_name='로그아웃 시간')),
                ('previous_session_terminated', models.BooleanField(default=False, verbose_name='기존 세션 종료됨')),
                ('previous_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='이전 로그인 IP')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '로그인 이력',
                'verbose_name_plural': '로그인 이력',
                'ordering': ['-login_at'],
                'indexes': [models.Index(fields=['user', '-login_at'], name='core_loginh_user_id_9b6879_idx'), models.Index(fields=['ip_address'], name='core_loginh_ip_addr_343b64_idx'), models.Index(fields=['login_at'], name='core_loginh_login_a_7c2d67_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True, verbose_name='세션 키')),
                ('token_key', models.CharField(blank=True, max_length=40, null=True, verbose_name='토큰 키')),
                ('current_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='현재 IP')),
                ('current_user_agent', models.TextField(blank=True, null=True, verbose_name='현재 User Agent')),
                ('current_device_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='현재 기기 유형')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='업데이트 시간')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='마지막 활동')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_session', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '사용자 세션',
                'verbose_name_plural': '사용자 세션',
                'indexes': [models.Index(fields=['session_key'], name='core_userse_session_1ee7ed_idx'), models.Index(fields=['token_key'], name='core_userse_token_k_85fce4_idx'), models.Index(fields=['last_activity'], name='core_userse_last_ac_9388f7_idx')],
            },
        ),
    ]
