# Generated by Django 5.0.3 on 2025-07-26 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_add_login_tracking_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='clinic_subject',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_clinics', to='core.subject', verbose_name='과목'),
        ),
        migrations.AlterField(
            model_name='user',
            name='subject',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='core.subject', verbose_name='과목'),
        ),
    ]
