# Generated by Django 5.0.3 on 2025-07-27 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_clinic_clinic_subject_alter_user_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='no_show',
            field=models.IntegerField(default=0, help_text='2회 이상 무단결석 시 보충 예약이 제한됩니다.', verbose_name='무단결석 횟수'),
        ),
        migrations.CreateModel(
            name='ClinicAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='출석을 체크한 날짜 (년-월-일)', verbose_name='출석 날짜')),
                ('attendance_type', models.CharField(choices=[('attended', '출석'), ('absent', '결석'), ('sick', '병결'), ('late', '지각')], max_length=10, verbose_name='출석 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시간')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.clinic', verbose_name='클리닉')),
                ('student', models.ForeignKey(limit_choices_to={'is_student': True}, on_delete=django.db.models.deletion.CASCADE, related_name='clinic_attendances', to=settings.AUTH_USER_MODEL, verbose_name='학생')),
            ],
            options={
                'verbose_name': '클리닉 출석',
                'verbose_name_plural': '클리닉 출석',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['student', '-date'], name='core_clinic_student_ebaed1_idx'), models.Index(fields=['clinic', '-date'], name='core_clinic_clinic__529a2b_idx'), models.Index(fields=['attendance_type'], name='core_clinic_attenda_42e6fe_idx')],
                'unique_together': {('clinic', 'student', 'date')},
            },
        ),
    ]
