# Generated by Django 5.0.3 on 2025-07-28 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_clinicattendance_attendance_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicattendance',
            name='attendance_type',
            field=models.CharField(choices=[('attended', '출석'), ('absent', '결석'), ('sick', '병결'), ('late', '지각'), ('none', '미정')], default='none', max_length=10, verbose_name='출석 상태'),
        ),
    ]
