# Generated by Django 5.0.3 on 2025-07-29 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_clinicattendance_attendance_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='clinic_teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_teacher': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_clinics', to=settings.AUTH_USER_MODEL, verbose_name='담당 강사'),
        ),
    ]
