# Generated by Django 5.0.3 on 2025-08-05 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_clinic_clinic_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicattendance',
            name='is_active',
            field=models.BooleanField(default=True, help_text='활성화된 출석 데이터만 조회 가능합니다.', verbose_name='활성화 상태'),
        ),
        migrations.AlterField(
            model_name='clinicattendance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='보충 예약 생성 시간'),
        ),
        migrations.AlterField(
            model_name='clinicattendance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='보충 예약 수정 시간'),
        ),
    ]
