# Generated by Django 5.0.3 on 2025-08-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_clinicattendance_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicattendance',
            name='date',
            field=models.DateField(blank=True, help_text='출석을 체크한 날짜 (년-월-일). 예약 생성 시에는 NULL, 출석 체크 시에만 설정됨.', null=True, verbose_name='출석 날짜'),
        ),
    ]
