# Generated by Django 5.0.3 on 2025-08-06 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_alter_clinicattendance_date"),
    ]

    operations = [
        # 먼저 기존 unique_together 제거 (date 필드가 포함되어 있음)
        migrations.AlterUniqueTogether(
            name="clinicattendance",
            unique_together=set(),
        ),
        # 기존 인덱스들 제거
        migrations.RemoveIndex(
            model_name="clinicattendance",
            name="core_clinic_student_ebaed1_idx",
        ),
        migrations.RemoveIndex(
            model_name="clinicattendance",
            name="core_clinic_clinic__529a2b_idx",
        ),
        # 기존 date 필드 제거
        migrations.RemoveField(
            model_name="clinicattendance",
            name="date",
        ),
        # 새 필드들 추가
        migrations.AddField(
            model_name="clinicattendance",
            name="actual_attendance_date",
            field=models.DateField(
                blank=True,
                help_text="실제로 출석을 체크한 날짜. 출석 상태를 업데이트할 때만 설정됨.",
                null=True,
                verbose_name="실제 출석 체크 날짜",
            ),
        ),
        migrations.AddField(
            model_name="clinicattendance",
            name="expected_clinic_date",
            field=models.DateField(
                default="2025-01-01",
                help_text="해당 주에서 클리닉이 열리는 예상 날짜 (클리닉 요일 기준으로 계산됨)",
                verbose_name="예상 클리닉 날짜",
            ),
        ),
        migrations.AddField(
            model_name="clinicattendance",
            name="reservation_date",
            field=models.DateField(
                default="2025-01-01",
                help_text="클리닉 예약을 생성한 날짜 (언제 예약했는지)",
                verbose_name="예약 생성 날짜",
            ),
        ),
        # 새 필드들이 추가된 후에 unique_together 변경
        migrations.AlterUniqueTogether(
            name="clinicattendance",
            unique_together={("clinic", "student", "expected_clinic_date")},
        ),
        # 모델 옵션 변경
        migrations.AlterModelOptions(
            name="clinicattendance",
            options={
                "ordering": ["-expected_clinic_date", "-created_at"],
                "verbose_name": "클리닉 출석",
                "verbose_name_plural": "클리닉 출석",
            },
        ),
        # 새 인덱스들 추가
        migrations.AddIndex(
            model_name="clinicattendance",
            index=models.Index(
                fields=["student", "-expected_clinic_date"],
                name="core_clinic_student_8324bf_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="clinicattendance",
            index=models.Index(
                fields=["clinic", "-expected_clinic_date"],
                name="core_clinic_clinic__80296d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="clinicattendance",
            index=models.Index(
                fields=["expected_clinic_date"], name="core_clinic_expecte_f6f35d_idx"
            ),
        ),
    ]
