# Generated by Django 5.0.3 on 2025-08-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_populate_attendance_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='non_pass',
            field=models.BooleanField(default=False, help_text='True인 경우 의무적으로 보충 클리닉을 수강해야 합니다.', verbose_name='의무 클리닉 대상자'),
        ),
    ]
