# Generated by Django 5.0.3 on 2025-08-19 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_user_non_pass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='clinic_students',
            field=models.ManyToManyField(blank=True, default=None, related_name='enrolled_clinics', to=settings.AUTH_USER_MODEL, verbose_name='예약한 학생들'),
        ),
        migrations.AlterField(
            model_name='clinicattendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_attendances', to=settings.AUTH_USER_MODEL, verbose_name='학생'),
        ),
        migrations.AlterField(
            model_name='studentplacement',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentplacement',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_placements', to=settings.AUTH_USER_MODEL),
        ),
    ]
