# Generated by Django 5.0.3 on 2025-09-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_clinic_clinic_students_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='essential_clinic',
            field=models.BooleanField(default=True, help_text='True인 경우 필수 클리닉을 신청하겠다는 뜻이고, False인 경우 필수 클리닉을 하지 않겠다는 뜻입니다.', verbose_name='필수 클리닉 신청'),
        ),
    ]
